name: check-email
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: 22f1000422@ds.study.iitm.ac.in
        run: echo "Hello, world!"
