name: check-email
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  check-email-name:
    runs-on: ubuntu-24.04
    name: check the email is there
    steps:
      - name: 22f1000422@ds.study.iitm.ac.in
        run: echo "Hello, world!"
